name: Custom WSA Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python and dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Ubuntu dependencies
        run: sudo apt-get update && sudo apt-get install -y e2fsprogs attr unzip qemu-utils python3-venv

      - name: Run WSA build script
        run: |
          echo "Starting real WSA build for x64..."

          mkdir -p output

          ./scripts/build_with_lspinit.sh \
            --arch x64 \
            --release-type retail \
            --root-sol magisk \
            --magisk-branch topjohnwu \
            --magisk-ver stable \
            --install-gapps \
            --remove-amazon

      - name: List output folder (debug)
        run: ls -lh output

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: WSA_Build
          path: output/*.7z
